# Generated by Django 5.0.4 on 2024-04-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar_default.jpg', upload_to='profile_pics', verbose_name='Аватар'),
        ),
    ]